### ISSUE TITLE
Feedback Request Beanstalk

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#2]
# Feedback Request Elastic Beanstalk
Permalink naar bestand: [AWS-18 Elastic Beanstalk](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-18%20Beanstalk.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?

**Comment by MJLippai** [comment]
Clear and concise summary. A good amount of keywords to elaborate on the topic are provided.

Sources are all from AWS and seem related to the topics discussed.

Helpful mindmap is included to have a good overview.
Other good quality images are provided to further showcase the topics discussed.

**Comment by NederLANA** [comment]
## Samenvatting
How is Beanstalk different than Lambda? When would you use Beanstalk instead of Lambda?

## Key Terms
Very rich on key terms, although sometimes it is not clear how the key terms are relevant to the topic.

## Opdracht
Assignment looks very cool!
