### ISSUE TITLE
Feedback Request CloudFront

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#3]
# Feedback Request CloudFront
Permalink naar bestand: [AWS-19 CloudFront](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-19%20CloudFront.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```
Deel de link van de issue met je groepsgenoten.

**Comment by MJLippai** [comment]
Clear description of the topic with and its advantages listed.

Very elaborate mindmap included.

Keyterms are added and provide additional insight.

Various helpful screenshots added.

Result is more than satisfactory.

**Comment by NederLANA** [comment]
The topic explains that Cloudfront is caching content? How does that caching compare to Elasticache, Redis, or DynamoDB caching?

Wow !!! Your explanation of how Cloudfront is activated when user initially queries content is very clear and very nice. I want to use this too :D
