### ISSUE TITLE
Feedback Request Route 53

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#4]
# Feedback Request Route 53
Permalink naar bestand: [AWS-20 Route 53](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-20%20Route53.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```
Deel de link van de issue met je groepsgenoten.

**Comment by MJLippai** [comment]
Clear description of the service, with a useful mindmap to further help visualize all the relevant elements.

Limited keywords but Henk has a very thorough Kewword database already and the service is clearly described.

The sources are AWS, so legitimate and thorough.
