### ISSUE TITLE
Feedback Request EFS

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#5]
# Feedback Request EFS
Permalink naar bestand: [AWS-21 EFS](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-21%20EFS.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```
Deel de link van de issue met je groepsgenoten.

**Comment by NederLANA** [comment]
## Samenvatting
De onderwerp is heel goed beschreven. En duidelijk.

## Key terms
Je kun specifieke sleutelworden naar een precies line/sleutelwoord op een andere pagina wijzen met:
[sleutel word]geenspatie(../cloud-practitioner-beschrijvingen.md#sleutel-word) 
zoiets

## Bronnen
Goed gedaan

## Opdracht
Stap voor stap is heel duidelijk, maar misschien zijn de volledig screenshots niet nodig? 

1) Ik begrijp het niet goed hoe zie jij je file gemonteerd is? Je kun een van de volgende commando gebruiken: cat, mount, findmnt, lsblk, df
2) Waarom gebruik je "touch" commando in de directory om een file to maken? Maak jij het niet op de bron file system, en nu kijken op de mount?

*Hier is een screenshot van mijn eigen mount check met command: $df -h
![image](https://user-images.githubusercontent.com/4924632/149097952-3f1f0b16-bffe-45f7-be76-38acba7338cb.png)

**Comment by henkvanderduim** [comment]
Dank voor je feedback.

De key-terms verwijzingen zijn op de door jou beschreven wijze gedaan. Ik begin altijd met een verwijzing naar het hele document. Daarna wordt het specifiek.

Als reactie op 1 en 2 verwijs ik je graag naar: https://docs.aws.amazon.com/efs/latest/ug/wt1-getting-started.html 
Daar staan alles stappen in die ik letterlijk heb gevolgd. Ik had uiteraard andere commando's kunnen gebruiken, maar daar heb ik niet voor gekozen.

**Comment by MJLippai** [comment]
Topic is properly summarized.

Mindmap gives a great overview of all the linked elements.

Bit difficult to follow the exercise since I am not familiar with AWS but the wealth of images gives a clear step by step breakdown of what Henk had done to test the EFS service.

No additional keyterms were provided for this particular service but as mentioned previously Henk already has a deep repository of key terms he has linked here as well.
