### ISSUE TITLE
Feedback Request DynamoDB

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#6]
Permalink naar het bestand: [AWS DynamoDB](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-22%20DynamoDB.md)

## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?

**Comment by MJLippai** [comment]
Summary is to the point. Mind map again provides a nice birds-eye-view.

Sources used are from AWS again. Can't go wrong there.

Lab done is from Amazon themselves, so great way to showcase the service.

Ample screenshots showing the lab worked out in a systematic fashion.
