### ISSUE TITLE
Feedback Request RDS en Aurora

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#7]
# Feedback Request RDS en Aurora
Permalink naar bestand: [AWS-23 RDS en Aurora](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-23%20RDS%2C%20Aurora.md)

## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?

**Comment by MJLippai** [comment]
RDS and Aurora are explained with its key features.

Images elaborating the use of the services in an architecture are provided.

Keyterms are limited but unclear if more are needed when the content provided already covers the requirements (unfamiliar with AWS).

Mindmap gives a nice point of reference again. 

The labs once again provide thorough practical application of the services.
