### ISSUE TITLE
Feedback Request Lambda

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#8]
Permalink naar bestand: [AWS-24-Lambda](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-24%20Lambda.md)

## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?

**Comment by MJLippai** [comment]
Good and thorough summary of service. Easy to make the connections with its Azure counterpart.

Useful Mindmap as usual provided and helpful.

Good number of keyterms to build on the provided content.

Labs are properly illustrated and Henk always makes sure to provide more than the minimum requirements for a topic.
