### ISSUE TITLE
Feedback Request SNS, SQS, EventBridge

### ISSUE THREAD

**Issue by henkvanderduim** [techgrounds/cloud-6-repo-henkvanderduim#9]
Permalink naar bestand: [AWS-25 SNS, SQS, EventBridge](https://github.com/techgrounds/cloud-6-repo-henkvanderduim/blob/main/04_Cloud_3/AWS-25%20SNS%2C%20SQS%2C%20Event%20Bridge.md)

## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?

**Comment by MJLippai** [comment]
SNS, SQS and EventBridge are all concisely described and elaborated on with accompanying images.

Keyterms provide good and needed clarification on used terms in the descriptions.

Sources as expected are from AWS and also one outside sources (beabetterdev.com) which gives further clarification on when best to use specific services.

Labs are impeccable as usual.
